### ISSUE TITLE
BUFFER_SHORTAGE

### ISSUE THREAD

**Issue by Im-JJ** [ESX-Org/es_extended#153]
Suddenly when i started the servr this came up, im not really good at coding overall. 
Somebody here that can help?

![buffer_shortage](https://user-images.githubusercontent.com/44684337/47950894-bfef1400-df59-11e8-93ac-74416c2b96e3.png)

**Comment by Valkatastz** [comment]
Did you setup your sql query for database connection in the server.cfg ? The host, username, password properly? That buffer shortage is shown often for incorrect database query. Other possible way is if you are using some outdated plugins for example: weashop version 1.0.0 will return that buffer_shortage because of broken SQL query in it redirects to the es_extended to look for it and vice versa.
