### ISSUE TITLE
Duplicating dropped items

### ISSUE THREAD

**Issue by Sph3x** [ESX-Org/es_extended#19]
dont no where to put this but when players drop money and fast relog they still have the money and can pick up the drop one

**Comment by JaroSound** [comment]
up. How can i disable money drop but not give?

**Comment by ElPumpo** [comment]
Can someone still verify that the issue persists?

**Comment by x0Z3ro0x** [comment]
Yes I will test this for you the moment I am able to get back into my server :)

**Comment by ElPumpo** [comment]
Its easy to save the player's invetory upon dropping stuff. I also want to make it so you  can configure if you want a timer, and fix the missleading word 'remove'

**Comment by nykroza** [comment]
I can confirm that the issue persist, you if set the drop timer to 2 minutes.
You remove X objects from your inventory, you wait a few seconds, you redrop the same items etc
It will drop the same item on ground each time you did it

**Comment by benzon** [comment]
This is still a problem with out doubt.

There is 3 issues.

You can drop the same item over and over again, there should be no timer on this it needs to insta drop, to avoid the duplication issue.

There is a issue where you drop item's and it will move it self to a new location, so you can sometimes find things wird locations where they where not dropped.

You can drop an item, log out and login to duplicate to, this is again because of the drop timer.

What should be done in make it impossible to drop item's when in a car, make it instant drop, add an animation for the drop, so it's visually shown something is dropped.

And stabilize the bag's drop point so it dont end up fucking up.
