### ISSUE TITLE
Add to ESX.PlayerData?

### ISSUE THREAD

**Issue by MJRamon** [ESX-Org/es_extended#20]
So, is there a way to add new variables from database into ESX.PlayerData, like firstname/lastname/etc from esx_identity, so we won't query MySQL every time to get this info and we could have handy tool?

**Comment by MJRamon** [comment]
Same thing goes for esx_license and many others addons. We could decrease DB load drastically with an elegant solution.

**Comment by Fita93** [comment]
Problem is not everyone has esx_identity, or license. So what you should do is edit the extended script by yourself (if you know what you're doing, obviously).

**Comment by MJRamon** [comment]
Sure. But why not to pull all data from user table by default at least?

**Comment by ArkSeyonet** [comment]
Because not everyone wants to put everything into ESX.PlayerData, and to do it that way would mean that they can't just pick and choose which scripts that they want since it'd try to store data from scripts that may not be present. Do it yourself if you want the feature. You could pull whatever you wanted from user table on YOUR server by default. The majority of esx is meant to be modular so you can pick and choose which parts that you want, but if you want these features then you need to add them after you download the base scripts.

**Comment by MJRamon** [comment]
If adding manually - yes, not worth. If doing it automatically based on field names (you a pulling with * anyway) - sounds like a good idea.

**Comment by ElPumpo** [comment]
We can just add a function to set the xPlayer name, so esx_identity can change player names.

**Comment by ElPumpo** [comment]
There's already `.get()` and `.set()` for xPlayer?! I've added `.setName()` to xPlayer so you can change the player name on spawn.
