### ISSUE TITLE
Ditch EssentialMode

### ISSUE THREAD

**Issue by ElPumpo** [ESX-Org/es_extended#418]
There's a couple of reasons to why we want to ditch ES:

- it makes installing esx even more confusing than it already is
- relationship with kanersps
- a lot of ES code is useless on ESX installs
- ditching ES will improve performance (server sided) due to for example not having to load player data twice

The ES code used in ESX is minimal, we use the group permission system, command handling but thats it and can very easily be implememted ourselves.

## Progress

- [x] implememt our own cash handling by make it an account, and old xPlayer functions can just reference to the account
- [x] handle player loading ourselves
- [ ] implement commands

**Comment by FlawwsX** [comment]
This would be great for new users and existing users. At least you won’t have players complaining about Essentialmode not working in the ESX discord. Personally, I believe that ESX without Essentialmode would be cool with a new name, but that’s just me.

**Comment by bilbodog** [comment]
It could be a good idea, the more you own yourself the better and the easier it is to fix stuff and know why stuff is going crazy sometimes.

So I support that decision.

**Comment by Duqino** [comment]
If you think its better for server and ESX. Why don't you just do it? I see only improvements and no negative sides

**Comment by SNIKRS** [comment]
"relationship with kanersps" LUL thats true that this guy doesnt rly like ESX or even YOU. x)

**Comment by benzon** [comment]
If you want to ditch EssentialMode adleest make it possible to log out and char switch with out having to do a full relog.

**Comment by ElPumpo** [comment]
Why benzon? ESX doesn't support character switching out of the box and I don't think its gonna come

**Comment by benzon** [comment]
Just wondering why not add char switching it would make sence, most use a hackish solution anyways.

**Comment by ElPumpo** [comment]
How would you implement it, and again ESX doesn't support it - and wont ever.

**Comment by benzon** [comment]
Right now it uses identifier to controle a user.

What could be a possibility is adding a unique id to the database so ex let's say mine is 1 and 5, when i join the server i get promted to select either 1 or 5, i select 5, from now on all data thats tagged to the key 5 is that profiles data.

You then do a server side table that says playerid is tied with Unique ID so when it's looking up data it gets the Unique ID from that table based on my playerid

player[playerId] = UniqueID so insted of identifier it looks up the UniqueID in the database - i know that is a rewright of stuff but it's a way it could be done.

and then a /logout command, that saves your data, unties your playerId with the unique ID and put's you back in to the char selection, if you wanna switch to the one with id 1.

**Comment by benzon** [comment]
Just to follow up right now it uses player.getIdentifier() that comes from essentialmode.

That is triggered when es:playerLoaded is triggered, what kashacters do it just delay this proccess really.

So when selecting a char you could have a function intercepting the id that is selected and use that as an identifier insted of steam id.

When that is triggered initiate the load loop that loads the char data etc.

**Comment by ElPumpo** [comment]
Gotta give you some credit for looking at the bigger picture. I'll admit I noticed that 99% don't update their esx Install. But frankly if you cant for example make scripts  use the new weight code then this framework aint for you anyways.

This is related because what im saying is that realisticly it feels like no one is going to utilize it if we were to implememt it. That kashcaracters script is well established for this kind of plug&play server owners /devs.
All these thing and the fact that we are not interested in multi characters.

And yes ES only parses your identifier on player load, really useless.å

**Comment by benzon** [comment]
I think it’s a shame its something you are not interested in, since this is for a lot of people are core feature now a days, and I think you can agree with me on that.

And kashcaracters dont rly work for plug and play it’s buggy there is a lot of different versions, a lot of work to be done, to fix every minor issue here and there, and get it fully working.

The reason I have not added this my self is because I like to get updates, and not having to do every update manually.

And I do feel like it’s something the community would love being added build in multichar support, and it would help ESX stand out even more from other frameworks, since it’s build in and native to the framework.

What could be done is using a config option to disable the feature and stick with one char like the it currently do.

What I could see happening with it being a part of ESX, would be some of the devs wanting to update there scripts to work with ESX, and the users buzzing that ESX now got build in Multi Char support.

And since in theory it should be quite easy to do, I do ffeel like it’s worth exploring, and I do feel that if you did a strawpoll you would see a lot of the community wanting this feature as a part of ESX.

**Comment by benzon** [comment]
Suggestion if you at lest could convert it in to using an auto generated DB id for the identifier, then you open up for others being able to make the multi char module instead.

And to check there is only one entry to a count in msyql that way it's a minor modification that needs to be done dev wize to create a module for multichar support.

Then it's only very few changes comapred to a lot of changes.

**Comment by ElPumpo** [comment]
https://github.com/ESX-Org/es_extended/commit/35a726685e81c7e74d13e05d6f9b8e4d5f9bea23 🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉
