### ISSUE TITLE
Ditch Steam identifier

### ISSUE THREAD

**Issue by ElPumpo** [ESX-Org/es_extended#456]
Steam identifier will be ditched with the removal of ES code. This is because this identifier half the time doesn't let us know if a player owns the game.

People can buy the game on R* and for example join the same server several times to farm starting money, we cant have that.

We will be switching to the only identifier that tells us that you own the game, the R* license.
For steam players they have a tied R* account they cant untie, so no way to farm starting money so easily.

**Comment by benzon** [comment]
I can see the thought behind that, but that would only be a major issue on none whitelisted servers to be honest.

Right now Essentialmode actually fucks it up since it wont allow a new steamid with the same licenseID then it wont load correct.

Licenses are harder to work with for bigger communitys, keeping track hu is hu when the name field is gone to is making it harder and harder.

**Comment by marciogalvao89** [comment]
i have that issue, people are using 10 different steams to make money exploit

**Comment by ElPumpo** [comment]
No worries update is out soon

**Comment by ElPumpo** [comment]
https://github.com/ESX-Org/es_extended/commit/35a726685e81c7e74d13e05d6f9b8e4d5f9bea23 🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉
