### ISSUE TITLE
(Enhancement) Add new commands and multi groups in database with easy hierarchy config that es_extended can read well while using xPlayer.getGroup

### ISSUE THREAD

**Issue by yosefij159** [ESX-Org/es_extended#558]
1º)
I use /setcoords a lot but many times while I'm scripting I need to go to certain place to take the coordinates (wich I don't know until I get there).
It would be nice be able to have some command (like /tpway  /tptoway  /setcoordsway) to do that.

2º)
/giveaccountmoney can only give you money, not take it, or set it.
I am thinking that this needs a change.
Two examples:
A) /setaccountmoney [playerid] [account] [amount] where amount can be 10 (set) or -10 (remove) or +10 (add)
B) /setaccountmoney [playerid] [account] [type] [amount]
where type is add, remove, set

3º)
(NOTE: I have 4 groups instead of 2: superadmin, admin, moderator, vip, user)
If I create a command with user as needed group I can easily do `add_principal group.moderator group.user` to allow moderators to use that command too, not problem with that.
But when I want to check if an player has moderator group, that's when it gets complicated.
If the user is admin or superadmin (in the database) when I use `xPlayer.getGroup()` obtains that group and doesn't detect the hierarchy (admin has moderators commands) so it returns false.

My current workaround is to use ace, something like this
`add_ace group.superadmin "staff.isSuperadmin" allow
add_ace group.admin "staff.isAdmin" allow
add_ace group.moderator "staff.isMod" allow`
and check if has that ace instead of check if what group has.
I think that EssentialMode had some hierarchy in groups hard coded. So it worked great, but it was hard coded and a nightmare to add new groups that way.

Anyways, I wanted to ask you if you could create something like that system.
Or maybe change groups column in the database to add multiples groups (the hierarchy is still a problem with this but at least o could check if has that group specific group).

I think  that with the current system, it would be hard to check if the player has Moderator and VIP groups, because i can not add two groups to the database and both of these groups inherit user but moderator does not inherit vip.

I hope this was not too messy.
Thank you!

**Comment by ElPumpo** [comment]
Too many different things in your "issue". Sure I'll implement a `/setaccountmoney` command and a command for teleporting to your current waypoint. Then the other "issues" you're having with permissions are not related to esx at all.

We use the ACL system and it works perfectly fine. If you're having problems with setting permissions for groups then you can do this for example:

- with ESX register command function parse group `moderator` as allowed
- add this to your configuration file `add_principal group.admin group.moderator` - this makes so all players with `admin` group gets access to all `moderator` allowed commands

And yes there's no way for ESX to detect if you're manually using `add_principal` on players, that's why you should stick to the `xPlayer.setGroup()` function to set player groups. There's no way for ESX to listen to when a player principal has changed.

Essentialmode just complicated things with its own little permission based system and not using the inbuilt ACL by FXServer

**Comment by vicegamingnetwork** [comment]
So to be clear, we would create our own version of ES ADMIN?

**Comment by yosefij159** [comment]
Brief summary of my third paragraph, the problem I have with the current system is the following:
-> How can I add two groups with differents permissions to a player?
Example: Moderator and VIP. And I need to say that the Moderators do NOT inherit the VIP permissions.
-> If in the database I can only save one group, how do I check with xPlayer.setGroup() if a user is Moderator AND Vip at the same time?

Those two points summed up my problem.
What I was trying to ask you if you could add support for multiples groups (saved in database) to easy check `if xPlayer.hasGroup('moderator') and xPlayer.hasGroup('vip') then ..... end`

**Comment by ElPumpo** [comment]
Then add a group which is both vip and moderator??

**Comment by yosefij159** [comment]
that is a temp fix and tedious to do, I have 1 group for users, 5 for vips (bronze, silver, gold, platinum, diamond) and 5 staff (superadmin, admin, moderator, reportassistant, thirdpartyconsultant) it is just too complicated with the current system, and if I need to check all this with xPlayer.hasGroup it will be a pain in the *ss.

**Comment by ElPumpo** [comment]
Then dont make your group system so complicated? If you want multi group support then you can implement it yourself

**Comment by ElPumpo** [comment]
And what do you think this is? Dont expect anything to be cust
