### ISSUE TITLE
Weight and limits

### ISSUE THREAD

**Issue by XvenDeR** [ESX-Org/es_extended#641]
How you guys deal with new weight system? I see this a little wrong... We want to make this as realistic as possible. BUT we have now a weight only system, which gives me headaches every time I'm trying to fix economy.

**Example 1:**
bread weights 100g, player can carry 25 kg = 250 breads? I hardly imagine myself carrying 250 breads.

**Better Example 2:**
1 big water barrel (200 liters), weights about 5 kg? = i can carry 5 barrels (and if we have a bag? its even worse)
(barrel [picture](https://www.quakekare.com/product/image/large/2c_55%20gallon%20drum.jpg))
literally you would be able to carry only 1 barrel with two hands.

**Solution:**
Use _weight_ AND _limit_ system together, this way it would be the most realistic as could be.

I had a hard time dealing with this. Your opinions, suggestions, tips and tricks? All appreciated. 👌

**Comment by TheTrueUprising** [comment]
If you figure out a way to do this please let me know because I'm also having alot of trouble trying to reduce the amount of items players are able to buy from my custom shops I even went as far as to revert back to an earlier version of this script to where it was just the limit system but now I get an error for add on inventory and this it's the last thing I need to fix before server release 
![20200408_031017](https://user-images.githubusercontent.com/61642667/78765603-39144700-7956-11ea-95b6-5eea2a2e036f.jpg)

**Comment by HumanTree92** [comment]
Just saying to carry the big blue barrel full of water you wouldn't even be able to pick it up with your hands. And if you could you wouldn't be able to walk 10ft with it. But yes i agree that having the limit as well is what we need.

**Comment by ElPumpo** [comment]
Just scale the item content amd weight accordingly if needes. And no limit is dead

**Comment by XvenDeR** [comment]
> Just saying to carry the big blue barrel full of water you wouldn't even be able to pick it up with your hands. And if you could you wouldn't be able to walk 10ft with it. But yes i agree that having the limit as well is what we need.

that should be an empty barrel for that example of course.

**Comment by NightcoreIsla** [comment]
i paste a way how to add limit on es_extended
u can try
https://github.com/ESX-Org/es_extended/issues/632
