### ISSUE TITLE
easy update its possible?

### ISSUE THREAD

**Issue by SliderKP** [ESX-Org/es_extended#844]
im using an older version of es_extended, i trying to update, but i see the database structure changes...

in my database with all my users info, names is: essentialmode and the new is es_extended, any way to update without lossing information ?

**Comment by TrinxudasDoZe** [comment]
AFAIK there's no direct update. You'd have to rewrite most of the script's code to work with the new esx, and some of them is just not possible yet, for example the inventory system, i don't think there's an API for using items yet. If you are a developer or wish get into this new esx, i encourage you to do so, otherwise you'll not be using this version anytime soon.

**Comment by SliderKP** [comment]
okey thanks for your help!

i going to continue using my versions :(
